import type { Metadata } from "next";
import { Geist_Mono as GeistMono } from "next/font/google";
import Header from "@/components/header";


const geistMono = GeistMono({
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-geist-mono", 
  weight: "variable"
});

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistMono.variable}`}>
      <body className="min-h-screen antialiased">
        <Header />
        {children}
      </body>
    </html>
  );
}